name: Update Menu Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  NODE_TLS_REJECT_UNAUTHORIZED: '0'
  API_TOKEN: ${{ secrets.MY_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: |
          if ! npx eslint .; then
            echo "Линтер нашел ошибки, но продолжаем для теста"
          fi

      - name: Run parser
        run: |
          mkdir -p public
          node public/index.js

      - name: Save Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: menu-data-reports
          path: public/*.json
          if-no-files-found: warn

      - name: Debug git
        run: |
          git status
          git diff

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add public/menu.json public/buffet.json

          if ! git diff --cached --quiet; then
            git commit -m "chore: automated menu update $(date)"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Notify on Failure
        if: failure()
        run: echo "Пайплайн упал! Отправка уведомления команде..."
